FROM alpine:3.21
ARG WUKONG_INSTALL_UFW=0
RUN apk add --no-cache openrc busybox-openrc nftables nftables-openrc fail2ban fail2ban-openrc openssh openssh-server openssh-server-common openssh-server-common-openrc nginx nginx-openrc iproute2 python3 procps
RUN if [ "$WUKONG_INSTALL_UFW" = 1 ]; then apk add --no-cache ufw; fi
CMD ["/sbin/init"]
